added homework_21_12 and additional task
Viktoriyadneprovskaya/homework pull request #12
Opened 2023-01-02 10:37 UTC by Viktoriyadneprovskaya

2023-01-06 09:09 UTC, YeaaaaH commented on homework_21_12_dop/src/StringMethods.java
> +    String str = "";
Why do you declare it?

2023-01-06 09:10 UTC, YeaaaaH commented on homework_21_12_dop/src/StringMethods.java
> +    StringMethods(String str) {
You don't need this constructor

2023-01-06 09:11 UTC, YeaaaaH commented on homework_21_12_dop/src/StringMethods.java
> +    public void validate(boolean a){
do you really need this method?

2023-01-06 09:11 UTC, YeaaaaH commented on homework_21_12_dop/src/StringMethods.java
> +//    public int povtor(String str) {
naming...

2023-01-06 09:14 UTC, YeaaaaH commented on homework_21_12_dop/src/StringMethods.java
> +    public void delChar(String str) {//не работает
you can make these methods static

2023-01-06 09:14 UTC, YeaaaaH requested changes
need to fix

2023-01-12 18:31 UTC, Viktoriyadneprovskaya commented on homework_21_12_dop/src/StringMethods.java
> +    String str = "";
deleted

2023-01-12 18:31 UTC, Viktoriyadneprovskaya commented on homework_21_12_dop/src/StringMethods.java
> +    StringMethods(String str) {
deleted

2023-01-12 18:35 UTC, Viktoriyadneprovskaya commented on homework_21_12_dop/src/StringMethods.java
> +    public void validate(boolean a){
this method is used to make output more readable and understandable
I mean to output string massage, but not a false or true

2023-01-12 18:35 UTC, Viktoriyadneprovskaya commented on homework_21_12_dop/src/StringMethods.java
> +//    public int povtor(String str) {
corrected

2023-01-12 18:36 UTC, Viktoriyadneprovskaya commented on homework_21_12_dop/src/StringMethods.java
> +    public void delChar(String str) {//не работает
done

2023-01-12 18:36 UTC, merged